version: '3.7'

services:
  app:
    container_name: application-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes:
      - ./:/app
    env_file:
      - ./.env