version: '3.7'
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./Backend/.env
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "devdb", "-U", "dev"]
      interval: 10s
      timeout: 45s
      retries: 10

  app:
    container_name: application
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    volumes:
      - ./:/app
    env_file:
      - ./Frontend/.env
      - ./Backend/.env