version: '3.7'

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    command:
      [ "-path", "./database/migrations", "-database",  $DATABASE_URL, "up" ]

  app:
    container_name: application-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    env_file:
      - ./.env